/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#baeed1",
        "tertiary-container": "#fc7c78",
        "surface-container-highest": "#dde4dd",
        "surface-variant": "#dde4dd",
        "tertiary-fixed-dim": "#ffb3af",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#711419",
        "secondary": "#376850",
        "surface-bright": "#f4fbf4",
        "on-tertiary-fixed-variant": "#842225",
        "surface-container-low": "#eef6ee",
        "surface-dim": "#d4dcd5",
        "outline": "#6c7a71",
        "primary-container": "#10b981",
        "secondary-fixed-dim": "#9ed2b5",
        "inverse-primary": "#4edea3",
        "on-tertiary-fixed": "#410005",
        "primary-fixed-dim": "#4edea3",
        "on-error-container": "#93000a",
        "primary": "#006c49",
        "surface-container-high": "#e3eae3",
        "tertiary-fixed": "#ffdad7",
        "inverse-on-surface": "#ebf3eb",
        "surface-container-lowest": "#ffffff",
        "surface": "#f4fbf4",
        "on-background": "#161d19",
        "background": "#f4fbf4",
        "tertiary": "#a43a3a",
        "on-primary-container": "#00422b",
        "on-surface": "#161d19",
        "error-container": "#ffdad6",
        "inverse-surface": "#2b322d",
        "on-error": "#ffffff",
        "on-primary-fixed": "#002113",
        "secondary-container": "#b7ebce",
        "surface-tint": "#006c49",
        "primary-fixed": "#6ffbbe",
        "error": "#ba1a1a",
        "on-primary-fixed-variant": "#005236",
        "on-surface-variant": "#3c4a42",
        "on-secondary-fixed-variant": "#1e4f3a",
        "outline-variant": "#bbcabf",
        "on-secondary-container": "#3c6c54",
        "on-primary": "#ffffff",
        "surface-container": "#e8f0e9",
        "on-secondary-fixed": "#002113",
        "on-secondary": "#ffffff"
      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: { "DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem" },
    },
  },
  plugins: [],
}

